name: Build dpdu-passthru

on:
  push:
    branches:
      - master
      - ci_test
    tags:
      - 'v*'

permissions:
  contents: write  # Required for creating a release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Get Version Info
      shell: bash
      run: |
        VERSION=$(git describe --tags --always --dirty)
        echo "BUILD_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build Solution
      run: msbuild driver/driver.sln /m /p:Configuration=Release /p:Platform=x86

    - name: Create Zip Archive
      run: |
        powershell -Command "Compress-Archive -Path driver/Release/*.dll, installer/install.bat installer/pdu_api_root.xml -DestinationPath dpdu-passthru-${{ env.BUILD_VERSION }}.zip"

    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dpdu-passthru
        path: dpdu-passthru-${{ env.BUILD_VERSION }}.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download Zip Artifact
      uses: actions/download-artifact@v4
      with:
        name: dpdu-passthru
        path: artifacts

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
