name: Build dpdu-passthru

on: 
  push:
    branches:
      - master
      - ci_test

jobs:
  build:
    runs-on: windows-latest  # Use Windows to build with MSVC

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1  # Sets up the Visual Studio environment

    - name: Get Version Info
      shell: bash
      run: |
        VERSION=$(git describe --tags --always --dirty)
        echo "BUILD_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build Solution
      run: msbuild driver/driver.sln /m /p:Configuration=Release /p:Platform=x86
      
    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dpdu-passthru-${{ env.BUILD_VERSION }}
        path: driver/Release/*.dll